version: "2"
services:
  front:
    image: tsears/react-weather-front
    build:
      context: .
      dockerfile: Dockerfile.front
    environment:
      APP_SHORTNAME: 'react-scaffold-front'
      APP_API_URL: 'http://back:8081'
    ports:
    - "9000:80"
    links:
    - back
  back:
    image: tsears/react-weather-back
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
    - "8081:8081"
    env_file: .env
networks:
  default:
